services:
  database:
    container_name: database
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5433:5432

  app:
    container_name: app
    build: .
    ports:
      - 3001:3001
    env_file:
      - .env
    restart: always
    depends_on:
      - database